[build-system]
requires = [
   	"appdirs==1.4.4",
	"argparse==1.4.0",
	"atomicwrites==1.4.0",
	"attrs==19.3.0",
	"certifi==2020.12.5",
	"chardet==4.0.0",
	"cleo==0.8.1",
	"click==7.1.2",
	"clikit==0.6.2",
	"colorama==0.4.4",
	"crashtest==0.3.1",
	"distlib==0.3.1",
	"filelock==3.0.12",
	"httplib2==0.19.0",
	"idna==2.10",
	"importlib-metadata==1.3.0",
	"markdown==3.3.3",
	"more-itertools==8.0.2",
	"packaging==20.0",
	"pastel==0.2.1",
	"pip-licenses==3.3.0",
	"pip-tools==5.5.0",
	"pipenv==2020.11.15",
	"plantuml-creator==1.0.7",
	"plantuml-gentools==0.1.2",
	"plantuml-markdown==3.4.2",
	"plantuml-wrapper==0.1.0",
	"plantuml2freemind==0.8.2",
	"plantuml==0.3.0",
	"pluggy==0.13.1",
	"ptable==0.9.2",
	"py2puml==0.3.1",
	"py==1.8.1",
	"pyaml==20.4.0",
	"pylev==1.3.0",
	"pyparsing==2.4.6",
	"pytest==5.3.2",
	"python-magic==0.4.22",
	"pytoml==0.1.21",
	"pytoolbox==14.0.0",
	"pytz==2021.1",
	"pyyaml==5.4.1",
	"requests==2.25.1",
	"ruamel-yaml==0.15.87",
	"six==1.13.0",
	"str2bool==1.1",
	"stringcase==1.2.0",
	"typing-extensions==3.7.4.3",
	"urllib3==1.26.3",
	"venv-run==0.1.0",
	"virtualenv-clone==0.5.4",
	"virtualenv==20.4.2",
	"wcwidth==0.1.8",
	"wheel==0.36.2",
	"zipp==0.6.0",
]
build-backend = "setuptools.build_meta"

[tool.tox]
envlist = 'py38'

[testenv]
deps = 'pytest'
commands = 'pytest'

