[build-system]
requires = [
    "appdirs==1.4.4",
	"argparse==1.4.0",
	"certifi==2020.12.5",
	"cfgv==3.2.0",
	"chardet==3.0.4",
	"click==7.1.2",
	"distlib==0.3.1",
	"filelock==3.0.12",
	"identify==1.5.14",
	"idna==2.10",
	"nodeenv==1.5.0",
	"packaging==20.0",
	"pbr==3.1.1",
	"pip-licenses==3.3.0",
	"pip-tools==5.5.0",
	"pipenv==2020.11.15",
	"pre-commit==2.10.1",
	"ptable==0.9.2",
	"pyaml==20.4.0",
	"pyparsing==2.4.6",
	"python-dotenv==0.15.0",
	"python-magic==0.4.22",
	"pytoml==0.1.21",
	"pytoolbox==14.0.0",
	"pytz==2021.1",
	"pyyaml==5.4.1",
	"requests==2.25.1",
	"six==1.13.0",
	"toml==0.10.2",
	"urllib3==1.26.3",
	"venv-run==0.1.0",
	"virtualenv-clone==0.5.4",
	"virtualenv==20.4.2",
	"wheel==0.36.2",
]
build-backend = "setuptools.build_meta"
